const logotext = "MARGOT";
const meta = {
    title: "Margot Stevens",
    description: "I’m Margot Stevens UX Designer Currently specialised on Immersive Experience, such as AR-VR-MR.",
};

const introdata = {
    title: "I’m Margot Stevens",
    animated: {
        first: "I love UX design",
        second: "I design cool immersive experiences",
        third: "I imagine UserJourney and Level Design",
    },
    description: "Hello, I'm an UX Designer currently specialised on Immersive Experience, such as AR-VR-MR.",
    your_img_url: "https://github.com/stevensmt/portfolio/blob/master/src/pages/home/4x/illustration.png?raw=true",
};

const dataabout = {
    title: "About me",
    aboutmeEN: "UX designer, I have specialized through my experiences in immersive technologies such as AR, VR and MR. My various experiences have enabled me to work on the different stages in the production of a solution, i.e. from research, through ideation, level design, right up to production. Personally, I believe that the testing, onboarding and iteration phases are important to ensure the highest quality creation.",
    aboutme: "UX designer, je me suis spécialisé à travers mes expériences dans les technologies immersives telles que l'AR, la VR et la MR. Mes différentes expériences m'ont permis de travailler sur les différentes étapes de productions d'une solution, c'est-à-dire, de la recherche, en passant par l'idéation, le Level design, jusqu'à la production. Personnellement, je trouve que les phases de test, d'onboarding et d'itération sont importantes pour permettre la création la plus qualitative.",
};
const worktimeline = [
    {
        jobtitle: "UX Design Immersive Experience",
        where: "Atos - Bezons (95)",
        date: "01/2021 - Aujourd'hui",
    },
    {
        jobtitle: "Apprenticeship UX Design Immersive Experience",
        where: "Atos - Bezons (95)",
        date: "2021-2022",
    },
    {
        jobtitle: "UX-UI Designer",
        where: "Fanprime - Paris (75)",
        date: "2019-2021",
    },
];
const jobtimeline = [
    {
        jobtitle: "Mastère Spécialisé IDE",
        where: "Gobelins & Cnam-Enjmin - Paris (75)",
        date: "2021-2022",
    },
    {
        jobtitle: "Mastère en alternance interactivité et UX Design",
        where: "IIM - Courbevoie (92)",
        date: "2019-2021",
    },
    {
        jobtitle: "DNA en Design Graphique",
        where: "ESAD - Valence (26)",
        date: "2016-2018",
    },
];
const skills = [{
        name: "Figma - FigJam",
        value: 90,
    },
    {
        name: "Blender",
        value: 60,
    },
    {
        name: "Photoshop",
        value: 80,
    },
    {
        name: "Illustrator",
        value: 70,
    },
    {
        name: "Unity",
        value: 60,
    },
    {
        name: "Unreal Engine",
        value: 60,
    },
    {
        name: "HoloLens",
        value: 90,
    },
];
const learn = [
    {
        jobtitle: "Certification PSPO1",
        date: "2023",
    },
    {
        jobtitle: "Notions de base de Hololens 2 : développer des applications de réalité mixte",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
    {
        jobtitle: "Utilisé Dynamics 364 Guides",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
    {
        jobtitle: "Bases de l’accessibilité du gaming",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },{
        jobtitle: "Bases de l’accéssibilité",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },{
        jobtitle: "Formation sur la dyslexie, en partenariat avec Made By Dyslexia",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
];
const services = [{
        title: "Workshop",
        description: "Organisation, création de l'emploi du temps en fonction du type de workshop (Discovery workshop, Empathy workshop, Design workshop, Priorization workshop), sélection des ateliers (ice-breaking, idéation… ), compte rendu et itération.",
        descriptionEn: "Organization, creation of the schedule according to the type of workshop (Discovery workshop, Empathy workshop, Design workshop, Priorization workshop), selection of workshops (ice-breaking, ideation... ), reporting and iteration.",
    },
    {
        title: "UX Research",
        description: "Recherche réalisée à partir d'une problématique, d'une entreprise, une situation… Tout d'abord, en commençant par une veille, des interviews, une analyse des données, une synthétisation pour pouvoir présenter la première étape avant d'itérer jusqu'à atteindre l'objectif souhaiter en prenant en compte le plus de point de vue possible.",
        descriptionEn: "Research carried out on the basis of a problem, a company, a situation... First of all, starting with a watch, interviews, data analysis, synthesis to be able to present the first step before iterating until the desired objective is reached, taking into account as many points of view as possible.",
    },
    {
        title: "Level Design",
        description: "On retrouve le level design dans le virtuel et le réel, mais sa construction reprend des étapes qui peuvent être similaires. Tout d'abord, il faut identifier le point de départ, l'utilisateur et l'objectif final. Une fois tout pris en compte, on utilise plusieurs outils (schéma, flowchart ...) pour définir les différentes étapes et le format que cela peut prendre. On essaye de faire tester le niveau le plus possible afin d'avoir un niveau le plus agréable pour l'utilisateur et répondant aux mieux à notre objectif.",
        descriptionEn: "Level design can be found in both the virtual and the real world, but its construction takes up stages that can be similar. First of all, we need to identify the starting point, the user and the final objective. Once all this has been taken into account, we use various tools (diagram, flowchart, etc.) to define the different stages and the format they can take. We try to have the level tested as much as possible, to ensure that it's as pleasant as possible for the user and best meets our objective.",
    },
    {
        title: "Prototypage",
        description: "Le prototypage permet d'expérimenter une idée rapidement et d'itérer en fonction des retours. Le format qu'il prend va dépendre de ce que l'on essaye de tester, ainsi, on peut le réaliser en low-fidelity, ou bien en se rapprochant de projet final. ",
        descriptionEn: "Prototyping allows you to test an idea quickly and iterate on the feedback. The format it takes will depend on what you're trying to test, so it can be low-fidelity, or closer to the final project. ",
    },
    {
        title: "VR Project",
        description: "Lors de la réalisation de projet en VR, j'ai eu la chance de pouvoir travailler sur les différentes étapes allant jusqu'à la production du Proof of concept. Que ce soit la recherche, la spécification, la création de maquette, le game design, Level design, la production d'assets 3D, leurs intégrations et l'ajout de l'interaction dans l'expérience VR sur Unity principalement. Puis la présentation du projet et la phase de testing.",
        descriptionEn: "When working on a VR project, I was lucky enough to be able to work on the various stages up to the production of the Proof of Concept. This included research, specification, model creation, game design, level design, production of 3D assets, their integration and the addition of interaction to the VR experience, mainly on Unity. Then the project presentation and testing phase.",
    },
    {
        title: "HoloLens",
        description: "Lors de la réalisation de projet HoloLens, j'ai eu la chance de pouvoir travailler sur les différentes étapes allant jusqu'à la production du Proof of concept. Que ce soit la recherche, la spécification, la création de maquette, le game design, Level design, la production d'assets 3D, leurs intégrations et l'ajout de l'interaction dans l'expérience VR sur Unity et Unreal. Puis la présentation du projet et la phase de testing.",
        descriptionEn: "While working on HoloLens projects, I was lucky enough to be able to work on the various stages up to the production of the Proof of Concept. This included research, specification, mock-up creation, game design, level design, production of 3D assets, their integration and the addition of interaction to the VR experience on Unity and Unreal. Then the project presentation and testing phase.",
    },
    {
        title: "Accessibility",
        description: "Je travaille principalement sur le sujet de l'accessibilité des expériences XR, dans l'idée de rendre mes expériences le plus accessibles possible, mais également de produire des expériences permettant de rendre plus accessible certaine situation pouvant être bloquante.",
        descriptionEn: "I'm mainly working on the accessibility of XR experiences, with the idea of making my experiences as accessible as possible, but also of producing experiences that make certain situations that can be blocking more accessible.",
    },
];


const dataportfolio = [{
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/these.png?raw=true",
        description: "Accessibility",
        link: "/these",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/research.png?raw=true",
        description: "Research",
        link: "/research",
    },

    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/MR.png?raw=true",
        description: "Mixed Reality",
        link: "/MixedReality",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/IceCube.png?raw=true",
        description: "Ice Cube",
        link: "/IceCube",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/workshop01.png?raw=true",
        description: "Workshop",
        link: "/workshop",
    },

    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/VR.png?raw=true",
        description: "Virtual Reality",
        link: "/VirtualReality",
    },

];


const icecube = {
    title: "Resume",
    resume: "Projet étudiant consistant en la production du onboarding d’un jeu. Notre groupe de quatre étudiants a produit Ice Cube - Ad memoriam, un jeu narratif en 2D réalisé en moins de 6 mois en parallèle de notre alternance.",
    resumeEN: "Student project consisting of the production of the onboarding of a game. Our group of four students produced Ice Cube - Ad memoriam, a 2D narrative game achieved in less than 6 months in parallel to our apprenticeship.",
    description: "here",
    link_game: "https://shynis.itch.io/ice-cubes",
    titleObj: "Goals",
    objectif: "Ice Cube est un projet de fin d'étude réalisé en parallèle de notre alternance. Nous étions un groupe de quatre et devions réaliser en moins de 6 mois une première expérience du jeu permettant de comprendre son principe. Nous avons réalisé un onboarding d'un plateformer narratif. Pendant la phase de production, j’ai tenu le rôle de Directrice Artistique, Lead Art et ai également tenu le rôle de Level Designer, UX & Motion Designer.",
    objectifEN: "Ice Cube is an end-of-study project carried out in parallel with our work-study program. We were a group of four, and in less than 6 months we had to create a first experience of the game, enabling us to understand its principle. We carried out onboarding for a narrative platformer. During the production phase, I took on the role of Art Director, Lead Art and also Level Designer, UX & Motion Designer.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/perso2.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/uiux.png?raw=true",
    title03: "UX-UI design",
    ENtext02: "- Sign", 
    ENtxt23: "- Graphic charter", 
    ENtxt24: "- Design system", 
    ENtxt25: "- Mockup and wireframe", 
    ENtxt26: "- HUD for the dialog box and the choice", 
    text02: "- Signe", 
    txt23: "- Charte graphique", 
    txt24: "- Design system", 
    txt25: "- Mockup et wireframe", 
    txt26: "- HUD des boîtes de dialogues et des choix", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/level.png?raw=true",
    title02: "Level design",
    ENtext03: "- Level pacing", 
    ENtxt33: "- Design of the environment and placement of the elements needed for the puzzle", 
    ENtxt34: "- Prioritization of tasks", 
    ENtxt35: "- Flow of the levels to guide the players", 
    ENtxt36: "- Schematization of the placement of set elements", 
    text03: "- Rythme des niveaux", 
    txt33: "- Conception de l'environnement et placement des éléments nécessaire pour l'énigme", 
    txt34: "- Priorisation des tâches", 
    txt35: "- Cheminement des niveaux pour guider les joueurs", 
    txt36: "- Schématisation de la mise en place des éléments de décors",
    none: "-   ", 
};
const MR = {
    title: "Resume",
    resume: "Production de projet en MR, présentation, démonstration et mise en place pour expliquer la prise en main de contrôler.",
    resumeEN: "Production of MR projects, presentation, demonstration and set-up to explain the handling of the controls.",
    titleObj: "Goals",
    objectif: "Lorsqu'on réalise un projet en MR l'objectif est de répondre à un besoin client identifié ou de présenter les possibilités techniques qu'apporte l'outil. Personnellement, travailler avec un tel outil me donne comme objectif de créer la meilleure expérience possible en prenant en compte que nous sommes en présence de média 3D.",
    objectifEN: "When working on an MR project, the aim is to meet an identified customer need, or to showcase the technical possibilities offered by the tool. Personally, working with such a tool gives me the objective of creating the best possible experience, bearing in mind that we're dealing with 3D media.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/01.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/02.png?raw=true",
    title03: "UX-UI design",
    text02: "- Facilitation", 
    txt23: "- Présentation", 
    txt24: "- Affordance et ergonomie", 
    txt25: "- Mockup and wireframe", 
    txt26: "- Étude de l'utilisateur (persona, userjourney ...)", 
    ENtext02: "- Facilitation", 
    ENtxt23: "- Presentation", 
    ENtxt24: "- Affordability and ergonomy", 
    ENtxt25: "- Mockup et wireframe", 
    ENtxt26: "- User study (persona, userjourney ...)", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/03.png?raw=true",
    title02: "Prototyping",
    text03: "- Modélisation 3D", 
    txt33: "- Test sur Unity ou Unreal Engine", 
    txt34: "- Test et itération", 
    txt35: "- Onboarding", 
    txt36: "- Level Design", 
    ENtext03: "- 3D modeling", 
    ENtxt33: "- Testing on Unity or Unreal Engine", 
    ENtxt34: "- Testing and iteration", 
    ENtxt35: "- Onboarding", 
    ENtxt36: "- Level Design",
    none: "-   ", 
};
const research = {
    title: "Resume",
    resume: "Chaque projet commence par une recherche, celle-ci continu pendant la phase d’idéation et de production. Le processus de prototypage permet de réaliser et tester des fonctionnalités et/ou outils pour définir le potentiel qu’il présente. Cela permet également de fonctionner par itération en testant et en modifiant le prototype.",
    resumeEN: "Each project starts with research, which continues during the ideation and production phase. The prototyping process allows for the development and testing of features and/or tools to define their potential. It also allows for iteration by testing and modifying the prototype.",
    titleObj: "Goals",
    objectif: "Lorsqu'un nouveau client ou sujet arrivent, nous devons proposer une solution au plus près de leur besoin. Mon objectif et donc de comprendre au mieux le client, l'utilisateur afin de définir dans quel espace, avec quelle technologie et quels sont leurs problématiques.",
    objectifEN: "When a new customer or subject arrives, we have to propose a solution that's as close as possible to their needs. My aim is to understand the customer, the user, in order to define the space, the technology and the issues they face.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/01.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/02.png?raw=true",
    title03: "UX Research",
    ENtext02: "- Study of the brand, the subject and the potential client", 
    ENtxt23: "- Persona", 
    ENtxt24: "- UserJourney and Flowchart", 
    ENtxt25: "- Design thinking tools such as 5W1H", 
    ENtxt26: "- Facilitation", 
    text02: "- Veille", 
    txt23: "- Persona", 
    txt24: "- UserJournay et Flowchart", 
    txt25: "- Outils de design thinking tel que 5W1H", 
    txt26: "- Facilitation", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/03.png?raw=true",
    title02: "Prototyping",
    ENtext03: "- UserJourney", 
    ENtxt33: "- Level Design", 
    ENtxt34: "- Low-fidelity prototype", 
    ENtxt35: "- Testing and iteration", 
    ENtxt36: "- Presentation", 
    text03: "- UserJourney", 
    txt33: "- Level Design", 
    txt34: "- Prototype low-fidelity", 
    txt35: "- Test et itération", 
    txt36: "- Présentation",
    none: "-   ", 
};
const these = {
    title: "Resume",
    resume: "L’accessibilité et les technologies XR sont des sujets que j’ai à plusieurs reprise rencontrées et sur lequel je travaille encore actuellement. A la base, cette étude a commencé avec ma thèse de fin d’étude, thèse de mastère spécialisé réalisé en 6 mois pendant notre alternance.",
    resumeEN: "The accessibility in XR technologies is a subject that I have encountered several times and on which I am still working. Basically, this study started with my end-of-study thesis, a specialised master's thesis carried out in 6 months during our apprenticeship.",

    titleObj: "Goals",
    objectif: "L'objectif de cette étude était de définir si les technologies XR peuvent être une source d'aide pour les personnes en situation de handicap, mais également de voir quels points doivent être pris en compte pour rendre le contenu accessible.",
    objectifEN: "The aim of this study was to define whether XR technologies can be a source of help for people with disabilities, but also to see what points need to be taken into account to make content accessible.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/01.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/02-ux.png?raw=true",
    title03: "UX-UI design",
    ENtext02: "- Qualitative interviews", 
    ENtxt23: "- QA testing", 
    ENtxt24: "- Mockup and Wireframe", 
    ENtxt25: "- UserJourney", 
    ENtxt26: "- Facilitation", 
    text02: "- Entretiens qualitatifs", 
    txt23: "- QA testing", 
    txt24: "- Mockup et Wireframe", 
    txt25: "- UserJourney", 
    txt26: "- Facilitation", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/03.png?raw=true",
    title02: "Research",
    ENtext03: "- Technology watch", 
    ENtxt33: "- Prototyping", 
    ENtxt34: "- Reading scientific reports", 
    ENtxt35: "- Facilitation", 
    ENtxt36: "- Presentation", 
    text03: "- Veille technologique", 
    txt33: "- Prototypage", 
    txt34: "- Lecture de rapport scientifique", 
    txt35: "- Facilitation", 
    txt36: "- Présentation",
    none: "-   ", 
};
const VR = {
    title: "Resume",
    resume: "Production de projet en VR, présentation, démonstration et mise en place pour expliquer la prise en main de contrôler.",
    resumeEN: "Production of VR projects, presentation, demonstration and set-up to explain the handling of the controls.",
    description: "here",
    link_game: "https://shynis.itch.io/ice-cubes",
    titleObj: "Goals",
    objectif: "Ice Cube est un projet de fin d'étude réalisé en parallèle de notre alternance. Nous étions un groupe de quatre et devions réaliser en moins de 6 mois une première expérience du jeu permettant de comprendre son principe. Nous avons réalisé un onboarding d'un plateformer narratif. Pendant la phase de production, j’ai tenu le rôle de Directrice Artistique, Lead Art et ai également tenu le rôle de Level Designer, UX & Motion Designer.",
    objectifEN: "Ice Cube is an end-of-study project carried out in parallel with our work-study program. We were a group of four, and in less than 6 months we had to create a first experience of the game, enabling us to understand its principle. We carried out onboarding for a narrative platformer. During the production phase, I took on the role of Art Director, Lead Art and also Level Designer, UX & Motion Designer.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/01.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/02.png?raw=true",
    title03: "UX-UI design",
    text02: "- Facilitation", 
    txt23: "- Présentation", 
    txt24: "- Affordance et ergonomie", 
    txt25: "- Mockup and wireframe", 
    txt26: "- Étude de l'utilisateur (persona, userjourney ...)", 
    ENtext02: "- Facilitation", 
    ENtxt23: "- Presentation", 
    ENtxt24: "- Affordability and ergonomy", 
    ENtxt25: "- Mockup et wireframe", 
    ENtxt26: "- User study (persona, userjourney ...)", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/03.png?raw=true",
    title02: "Level Design & Onboarding",
    ENtext03: "- Level pacing", 
    ENtxt33: "- Design of the environment and placement of the elements needed for the puzzle", 
    ENtxt34: "- Prioritization of tasks", 
    ENtxt35: "- Flow of the levels to guide the players", 
    ENtxt36: "- Schematization of the placement of set elements", 
    text03: "- Rythme des niveaux", 
    txt33: "- Conception de l'environnement et placement des éléments nécessaire pour l'énigme", 
    txt34: "- Priorisation des tâches", 
    txt35: "- Cheminement des niveaux pour guider les joueurs", 
    txt36: "- Schématisation de la mise en place des éléments de décors",
    none: "-   ", 
};
const workshop = {
    title: "Resume",
    resume: "Projet étudiant consistant en la production du onboarding d’un jeu. Notre groupe de quatre étudiants a produit Ice Cube - Ad memoriam, un jeu narratif en 2D réalisé en moins de 6 mois en parallèle de notre alternance.",
    resumeEN: "Student project consisting of the production of an onboarding game. Our group of four students produced Ice Cube - Ad memoriam, a 2D narrative game achieved in less than 6 months in parallel to our apprenticeship.",
    description: "here",
    link_game: "https://shynis.itch.io/ice-cubes",
    titleObj: "Goals",
    objectif: "Ice Cube est un projet de fin d'étude réalisé en parallèle de notre alternance. Nous étions un groupe de quatre et devions réaliser en moins de 6 mois une première expérience du jeu permettant de comprendre son principe. Nous avons réalisé un onboarding d'un plateformer narratif. Pendant la phase de production, j’ai tenu le rôle de Directrice Artistique, Lead Art et ai également tenu le rôle de Level Designer, UX & Motion Designer.",
    objectifEN: "Ice Cube is an end-of-study project carried out in parallel with our work-study program. We were a group of four, and in less than 6 months we had to create a first experience of the game, enabling us to understand its principle. We carried out onboarding for a narrative platformer. During the production phase, I took on the role of Art Director, Lead Art and also Level Designer, UX & Motion Designer.",
    img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/perso2.png?raw=true",   
    img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/uiux.png?raw=true",
    title03: "UX-UI design",
    ENtext02: "- Sign", 
    ENtxt23: "- Graphic charter", 
    ENtxt24: "- Design system", 
    ENtxt25: "- Mockup and wireframe", 
    ENtxt26: "- HUD for the dialog box and the choice", 
    text02: "- Signe", 
    txt23: "- Charte graphique", 
    txt24: "- Design system", 
    txt25: "- Mockup et wireframe", 
    txt26: "- HUD des boîtes de dialogues et des choix", 
    img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/level.png?raw=true",
    title02: "Level design",
    ENtext03: "- Level pacing", 
    ENtxt33: "- Design of the environment and placement of the elements needed for the puzzle", 
    ENtxt34: "- Prioritization of tasks", 
    ENtxt35: "- Flow of the levels to guide the players", 
    ENtxt36: "- Schematization of the placement of set elements", 
    text03: "- Rythme des niveaux", 
    txt33: "- Conception de l'environnement et placement des éléments nécessaire pour l'énigme", 
    txt34: "- Priorisation des tâches", 
    txt35: "- Cheminement des niveaux pour guider les joueurs", 
    txt36: "- Schématisation de la mise en place des éléments de décors",
    none: "-   ", 
};



const socialprofils = {
    cv: "https://github.com",
    linkedin: "https://linkedin.com",
    email: "m.stevens@protonmail.com",
};
export {
    meta,
    dataabout,
    dataportfolio,
    worktimeline,
    jobtimeline,
    skills,
    learn,
    services,
    introdata,
    socialprofils,
    logotext,
    icecube,
    MR,
    research,
    these,
    VR,
    workshop,
};