const logotext = "MARGOT";
const meta = {
    title: "Margot Stevens",
    description: "Je suis Margot Stevens, UX designer actuellement spécialisé dans l'immersive expérience, c'est-à-dire les technologies AR-VR-MR.",
};

const introdata = {
    title: "I’m Margot Stevens",
    animated: {
        first: "I love UX design",
        second: "I design cool immersive experiences",
        third: "I imagine UserJourney and Level Design",
    },
    description: "Bonjour, je suis UX designer, actuellement spécialisé dans l'immersive expérience, c'est-à-dire les technologies AR-VR-MR.",
    your_img_url: "https://github.com/stevensmt/portfolio/blob/master/src/pages/home/img/4x/03.png?raw=true",
};

const dataabout = {
    title: "About me",
    aboutmeEN: "UX designer, I have specialized through my experiences in immersive technologies such as AR, VR and MR. My various experiences have enabled me to work on the different stages in the production of a solution, i.e. from research, through ideation, level design, right up to production. Personally, I believe that the testing, onboarding and iteration phases are important to ensure the highest quality creation.",
    aboutme: "UX designer, je me suis spécialisé à travers mes expériences dans les technologies immersives telles que l'AR, la VR et la MR. Mes différentes expériences m'ont permis de travailler sur les différentes étapes de production d'une solution, c'est-à-dire, de la recherche, en passant par l'idéation, le Level design, jusqu'à la production. Personnellement, je trouve que les phases de test, d'onboarding et d'itération sont importantes pour permettre la création la plus qualitative.",
};
const worktimeline = [
    {
        jobtitle: "UX Design Immersive Experience",
        where: "Atos - Bezons (95)",
        date: "01/2021 - Aujourd'hui",
    },
    {
        jobtitle: "Contrat Apprentissage UX Design Immersive Experience",
        where: "Atos - Bezons (95)",
        date: "2021-2022",
    },
    {
        jobtitle: "Contrat Apprentissage UX-UI Designer",
        where: "Fanprime - Paris (75)",
        date: "2019-2021",
    },
];
const jobtimeline = [
    {
        jobtitle: "Mastère Spécialisé IDE",
        where: "Gobelins & Cnam-Enjmin - Paris (75)",
        date: "2021-2022",
    },
    {
        jobtitle: "Mastère en alternance interactivité et UX Design",
        where: "IIM - Courbevoie (92)",
        date: "2019-2021",
    },
    {
        jobtitle: "DNA en Design Graphique",
        where: "ESAD - Valence (26)",
        date: "2016-2018",
    },
];
const skills = [{
        name: "Figma - FigJam",
        value: 90,
    },
    {
        name: "Blender",
        value: 60,
    },
    {
        name: "Photoshop",
        value: 80,
    },
    {
        name: "Illustrator",
        value: 70,
    },
    {
        name: "Unity",
        value: 60,
    },
    {
        name: "Unreal Engine",
        value: 60,
    },
    {
        name: "HoloLens",
        value: 90,
    },
];
const learn = [
    {
        jobtitle: "Certification PSPO1",
        date: "2023",
    },
    {
        jobtitle: "Notions de base de Hololens 2 : développer des applications de réalité mixte",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
    {
        jobtitle: "Utilisé Dynamics 364 Guides",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
    {
        jobtitle: "Bases de l’accessibilité du gaming",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },{
        jobtitle: "Bases de l’accéssibilité",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },{
        jobtitle: "Formation sur la dyslexie, en partenariat avec Made By Dyslexia",
        where: "Trophée Microsoft Learn",
        date: "2022",
    },
];
const services = [{
        title: "Workshop",
        description: "Organisation, création de l'emploi du temps en fonction du type de workshop (Discovery workshop, Empathy workshop, Design workshop, Priorization workshop), sélection des ateliers (ice-breaking, idéation… ), compte rendu et itération.",
        descriptionEn: "Organization, creation of the schedule according to the type of workshop (Discovery workshop, Empathy workshop, Design workshop, Priorization workshop), selection of workshops (ice-breaking, ideation... ), reporting and iteration.",
    },
    {
        title: "UX Research",
        description: "Recherche réalisée à partir d'une problématique, d'une entreprise, une situation… Tout d'abord, en commençant par une veille, des interviews, une analyse des données, une synthétisation pour pouvoir présenter la première étape avant d'itérer jusqu'à atteindre l'objectif souhaité en prenant en compte le plus de points de vue possible.",
        descriptionEn: "Research carried out on the basis of a problem, a company, a situation... First of all, starting with a watch, interviews, data analysis, synthesis to be able to present the first step before iterating until the desired objective is reached, taking into account as many points of view as possible.",
    },
    {
        title: "Level Design",
        description: "On retrouve le level design dans le virtuel et le réel, mais sa construction reprend des étapes qui peuvent être similaires. Tout d'abord, il faut identifier le point de départ, l'utilisateur et l'objectif final. Une fois tout pris en compte, on utilise plusieurs outils (schéma, flowchart ...) pour définir les différentes étapes et le format que cela peut prendre. On essaye de faire tester le niveau le plus possible afin d'avoir un niveau le plus agréable pour l'utilisateur et répondant au mieux à notre objectif.",
        descriptionEn: "Level design can be found in both the virtual and the real world, but its construction takes up stages that can be similar. First of all, we need to identify the starting point, the user and the final objective. Once all this has been taken into account, we use various tools (diagram, flowchart, etc.) to define the different stages and the format they can take. We try to have the level tested as much as possible, to ensure that it's as pleasant as possible for the user and best meets our objective.",
    },
    {
        title: "Prototypage",
        description: "Le prototypage permet d'expérimenter une idée rapidement et d'itérer en fonction des retours. Le format qu'il prend va dépendre de ce que l'on essaye de tester, ainsi, on peut le réaliser en low-fidelity, ou bien en se rapprochant de projet final. ",
        descriptionEn: "Prototyping allows you to test an idea quickly and iterate on the feedback. The format it takes will depend on what you're trying to test, so it can be low-fidelity, or closer to the final project. ",
    },
    {
        title: "VR Project",
        description: "Lors de la réalisation de projets en VR, j'ai eu la chance de pouvoir travailler sur les différentes étapes allant jusqu'à la production du Proof of concept. Que ce soit la recherche, la spécification, la création de maquette, la game design, Level design, la production d'assets 3D, leurs intégrations et l'ajout de l'interaction dans l'expérience VR sur Unity principalement. Puis la présentation du projet et la phase de testing.",
        descriptionEn: "When working on a VR project, I was lucky enough to be able to work on the various stages up to the production of the Proof of Concept. This included research, specification, model creation, game design, level design, production of 3D assets, their integration and the addition of interaction to the VR experience, mainly on Unity. Then the project presentation and testing phase.",
    },
    {
        title: "HoloLens",
        description: "Lors de la réalisation de projets HoloLens, j'ai eu la chance de pouvoir travailler sur les différentes étapes allant jusqu'à la production du Proof of concept. Que ce soit la recherche, la spécification, la création de maquette, la game design, Level design, la production d'assets 3D, leurs intégrations et l'ajout de l'interaction dans l'expérience VR sur Unity et Unreal. Puis la présentation du projet et la phase de testing.",
        descriptionEn: "While working on HoloLens projects, I was lucky enough to be able to work on the various stages up to the production of the Proof of Concept. This included research, specification, mock-up creation, game design, level design, production of 3D assets, their integration and the addition of interaction to the VR experience on Unity and Unreal. Then the project presentation and testing phase.",
    },
    {
        title: "Accessibility",
        description: "Je travaille principalement sur le sujet de l'accessibilité des expériences XR, dans l'idée de rendre mes expériences les plus accessibles possible, mais également de produire des expériences permettant de rendre plus accessible certaine situation pouvant être bloquante.",
        descriptionEn: "I'm mainly working on the accessibility of XR experiences, with the idea of making my experiences as accessible as possible, but also of producing experiences that make certain situations that can be blocking more accessible.",
    },
];


const dataportfolio = [    

    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/VR.png?raw=true",
        description: "Virtual Reality project",
        link: "/portfolio/VirtualReality",
    },
    
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/workshop01.png?raw=true",
        description: "Workshop",
        link: "/portfolio/Workshop",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/MR.png?raw=true",
        description: "Mixed Reality project",
        link: "/portfolio/MixedReality",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/these.png?raw=true",
        description: "Accessibility",
        link: "/portfolio/These",
    },
    {
        img: "https://github.com/stevensmt/portfolio/blob/master/src/assets/images/IceCube.png?raw=true",
        description: "Ice Cube",
        link: "/portfolio/IceCube",
    },
];



const icecube = {
    Where:"Cnam-Enjmin",
    Where2: "Gobelins - École de l'image",
    Title01: "Catégories",
    info01: "Jeux vidéo",
    info012: "Projet étudiant en équipe",
    Title02: "Rôles",
    info02: "Lead Art",
    info022: "2D Artist",
    info023: "UX/UI designer",
    info024: "Level Designer",
    Title03: "Années",
    info03: "2022",
    Title04: "Outils",
    info04: "Photoshop, illustrator, Figma, Unity, Github, Notion, AfterEffect ...",
    ResumeTitle: "Résumé",
    ResumeTxt: "Ice Cube est un jeu narratif, où vous redéfinissez la mémoire de tout un village. Vous incarnez un esprit revenu sur terre pour aider à faire évoluer un village. Au cours de votre aventure vous récolterez des glaçons emprisonnant des souvenirs, à vous de voir si vous voulez vous en souvenirs ou les oublier. Porté par mon équipe et moi-même dans le cadre du Mastère IDE (double diplôme Gobelins – Cnam-Enjmin), ce jeu a été développé entre février et mai 2022 avec une durée effective d’un mois et demi de travail. Ice Cube est pour moi ma première expérience sur un jeu vidéo en tant que Lead Art. Outre la gestion de la direction artistique du jeu, j'étais en charge de la production des assets 2D, de l'UX et de l'UI, et d'une partie du Level design.",
    link_game: "https://shynis.itch.io/ice-cubes",
    description: "Play here",
    GoalsTitle: "Objectif",
    GoalsTxt:"Le jeu propose une narration interactive faisant évoluer l'environnement en fonction des choix du joueur. Nous voulions un décor évolutif, où l'impact de nos choix sont réellement visibles. L'esthétique se veut épurée et s'inspire de villages Ardéchois et Drômois, mais également de l’illustrateur Jirō Taniguchi, de l’artiste Michiel Scrijver, et des jeux Sky : the children of light et Gris.",
    GoalsTxt2: "Le jeu est en 2D avec un déplacement vertical, nous nous situons à flanc de montagne à son sommet. En évoluant dans le jeu, nous descendons peu à peu la montagne, faisant par la même occasion évoluer la palette graphique. ",
    DeroulementTxt: "Lors de la création des différents assets graphiqués, j'ai dû effectuer une première ébauche du Level design pour aider à prioriser la production des différents assets. Ce schéma avait pour but de définir les différentes étapes qui doivent se succéder afin de comprendre les mécanismes du jeu et de permettre aux joueurs de mieux comprendre et évoluer dans l'espace. Lors du playtest, le déroulement du Level design a aidé les différents joueurs à évoluer et nous a permis de mettre en avant un point problématique, l'UX-UI design. Suite à ce playtest, nous avons décidé de ralentir la production des assets graphique pour me permettre de reprendre en main la UX-UI design du jeu et la production des différents assets nécessaire.",
    DeroulementTxt2: "Les zones textuelles ont été mises en place par une collègue et de mon côté j'ai commencé un travail sur les signes, UI permettant de mettre en avant les éléments graphique et expliquant à l'utilisateur comment interagir avec. Ses assets ont été réalisés sur Figma, ce qui nous a permis de mettre en condition. Tous les assets graphiques ont également été intégrés au Figma afin de réaliser des maquettes pour permettre de faciliter le travail de la personne s'occupant de l'intégration.",
    Img1: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/img.png?raw=true",
    Img2: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/02.png?raw=true",
    Img3: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/003.png?raw=true",
    Img4: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/level.png?raw=true",
    Img5: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/01.png?raw=true",


    // title: "Information",
    // resume: "Projet étudiant consistant en la production du onboarding d’un jeu. Notre groupe de quatre étudiants a produit Ice Cube - Ad memoriam, un jeu narratif en 2D réalisé en moins de 6 mois en parallèle de notre alternance.",
    // resumeEN: "Student project consisting of the production of the onboarding of a game. Our group of four students produced Ice Cube - Ad memoriam, a 2D narrative game achieved in less than 6 months in parallel to our apprenticeship.",
    // titleObj: "Goals",
    // objectif: "Ice Cube est un projet de fin d'étude réalisé en parallèle de notre alternance. Nous étions un groupe de quatre et devions réaliser en moins de 6 mois une première expérience du jeu permettant de comprendre son principe. Nous avons réalisé un onboarding d'un plateformer narratif. Pendant la phase de production, j’ai tenu le rôle de Directrice Artistique, Lead Art et ai également tenu le rôle de Level Designer, UX & Motion Designer.",
    // objectifEN: "Ice Cube is an end-of-study project carried out in parallel with our work-study program. We were a group of four, and in less than 6 months we had to create a first experience of the game, enabling us to understand its principle. We carried out onboarding for a narrative platformer. During the production phase, I took on the role of Art Director, Lead Art and also Level Designer, UX & Motion Designer.",
    // img_link01: "https://images.pexels.com/photos/1133957/pexels-photo-1133957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    // //https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/perso2.png?raw=true",   
    // img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/uiux.png?raw=true",
    // title03: "UX-UI design",
    // ENtext02: "- Sign", 
    // ENtxt23: "- Graphic charter", 
    // ENtxt24: "- Design system", 
    // ENtxt25: "- Mockup and wireframe", 
    // ENtxt26: "- HUD for the dialog box and the choice", 
    // text02: "- Signe", 
    // txt23: "- Charte graphique", 
    // txt24: "- Design system", 
    // txt25: "- Mockup et wireframe", 
    // txt26: "- HUD des boîtes de dialogues et des choix", 
    // img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/IceCube/level.png?raw=true",
    // title02: "Level design",
    // ENtext03: "- Level pacing", 
    // ENtxt33: "- Design of the environment and placement of the elements needed for the puzzle", 
    // ENtxt34: "- Prioritization of tasks", 
    // ENtxt35: "- Flow of the levels to guide the players", 
    // ENtxt36: "- Schematization of the placement of set elements", 
    // text03: "- Rythme des niveaux", 
    // txt33: "- Conception de l'environnement et placement des éléments nécessaire pour l'énigme", 
    // txt34: "- Priorisation des tâches", 
    // txt35: "- Cheminement des niveaux pour guider les joueurs", 
    // txt36: "- Schématisation de la mise en place des éléments de décors",
    // none: "-   ", 
    nextLink:"/portfolio/Workshop",
    backLink:"/portfolio/MixedReality",
};
const MR = {
    Title01: "Catégories",
    info01: "Mixed Reality project",
    info012: "Collaboration",
    Title02: "Rôles",
    info02: "UX-UI Design",

    Title03: "Années",
    info03: "2023",
    Title04: "Outils",
    info04: "Unity, Unreal Engine, Blender, Figma, FigJam, ...",
    ResumeTitle: "Résumé",
    ResumeTxt: "Expérience HoloLens permettant à plusieurs utilisateurs de se connecter sur la même expérience et de dessiner ensemble.",
    GoalsTitle: "Objectif",
    GoalsTxt:"L'objectif était dans un premier temps à tester le système multijoueur sur HoloLens, et de proposer une expérience collaborative où l'utilisateur pourrait expérimenter librement.",
    GoalsTxt2: "L'idée est de proposer un outil pouvant être utilisé pour permettre à plusieurs utilisateurs de réfléchir et expérimenter ensemble. Outils pouvant être utilisés pendant les phases de workshop, de design thinking ou même de schématisation, cela permet de faciliter le partage des idées et d'interagir à distance avec des personnes pouvant se trouver dans un autre pays. Le projet se veut affordant et simple d'utilisation.",
    DeroulementTxt: "Un premier prototype a été réalisé pour tester la faisabilité technique et faire une veille sur les technologies a utilisé. Ce premier prototype se voulait au plus simple et ne permettait que de rejoindre une expérience collaborative, dessiner et effacer, celui-ci fut testé afin auprès d'utilisateur connaissant plus ou moins l'outil afin de vérifier sa bonne prise en main et son utilisation. La première phase de test nous a permis d'identifier les fonctionnalités à rajouter en priorité et les contrôles à mettre en place. J'ai donc effectué de nombreuses maquettes partagées avec le développer afin de fonctionner étape par étapes avec lui afin de réaliser une nouvelle version de l'expérience.",
    DeroulementTxt2: "Le premier prototype découle d'un questionnement sur l'accessibilité. Je voulais réaliser un premier test pour savoir si la connexion de plusieurs HoloLens en direct était possible et surtout permettait d'interagir en live ensemble. Je voulais également vérifier si les gestes de l'HoloLens était bien affordant. L'outil a évolué par la suite et m'a permis de valider mes questionnements.",
    Img1: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/001.png?raw=true",
    Img2: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/002.png?raw=true",
    Img3: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/003.png?raw=true",
    Img4: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/004.png?raw=true",
    Img5: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/005.png?raw=true",
    
    nextLink:"/portfolio/IceCube",
    backLink:"/portfolio/VirtualReality",

    // title: "Resume",
    // resume: "Production de projet en MR, présentation, démonstration et mise en place pour expliquer la prise en main de contrôler.",
    // resumeEN: "Production of MR projects, presentation, demonstration and set-up to explain the handling of the controls.",
    // titleObj: "Goals",
    // objectif: "Lorsqu'on réalise un projet en MR l'objectif est de répondre à un besoin client identifié ou de présenter les possibilités techniques qu'apporte l'outil. Personnellement, travailler avec un tel outil me donne comme objectif de créer la meilleure expérience possible en prenant en compte que nous sommes en présence de média 3D.",
    // objectifEN: "When working on an MR project, the aim is to meet an identified customer need, or to showcase the technical possibilities offered by the tool. Personally, working with such a tool gives me the objective of creating the best possible experience, bearing in mind that we're dealing with 3D media.",
    // img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/01.png?raw=true",   
    // img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/02.png?raw=true",
    // title03: "UX-UI design",
    // text02: "- Facilitation", 
    // txt23: "- Présentation", 
    // txt24: "- Affordance et ergonomie", 
    // txt25: "- Mockup and wireframe", 
    // txt26: "- Étude de l'utilisateur (persona, userjourney ...)",
    // ENtext02: "- Facilitation", 
    // ENtxt23: "- Presentation", 
    // ENtxt24: "- Affordability and ergonomy", 
    // ENtxt25: "- Mockup et wireframe", 
    // ENtxt26: "- User study (persona, userjourney ...)", 
    // img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/MixedReality/03.png?raw=true",
    // title02: "Prototyping",
    // text03: "- Modélisation 3D", 
    // txt33: "- Test sur Unity ou Unreal Engine", 
    // txt34: "- Test et itération", 
    // txt35: "- Onboarding", 
    // txt36: "- Level Design", 
    // ENtext03: "- 3D modeling", 
    // ENtxt33: "- Testing on Unity or Unreal Engine", 
    // ENtxt34: "- Testing and iteration", 
    // ENtxt35: "- Onboarding", 
    // ENtxt36: "- Level Design",
    // none: "-   ", 
};
// const research = {
//     title: "Resume",
//     resume: "Chaque projet commence par une recherche, celle-ci continu pendant la phase d’idéation et de production. Le processus de prototypage permet de réaliser et tester des fonctionnalités et/ou outils pour définir le potentiel qu’il présente. Cela permet également de fonctionner par itération en testant et en modifiant le prototype.",
//     resumeEN: "Each project starts with research, which continues during the ideation and production phase. The prototyping process allows for the development and testing of features and/or tools to define their potential. It also allows for iteration by testing and modifying the prototype.",
//     titleObj: "Goals",
//     objectif: "Lorsqu'un nouveau client ou sujet arrivent, nous devons proposer une solution au plus près de leur besoin. Mon objectif et donc de comprendre au mieux le client, l'utilisateur afin de définir dans quel espace, avec quelle technologie et quels sont leurs problématiques.",
//     objectifEN: "When a new customer or subject arrives, we have to propose a solution that's as close as possible to their needs. My aim is to understand the customer, the user, in order to define the space, the technology and the issues they face.",
//     img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/01.png?raw=true",   
//     img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/02.png?raw=true",
//     title03: "UX Research",
//     ENtext02: "- Study of the brand, the subject and the potential client", 
//     ENtxt23: "- Persona", 
//     ENtxt24: "- UserJourney and Flowchart", 
//     ENtxt25: "- Design thinking tools such as 5W1H", 
//     ENtxt26: "- Facilitation", 
//     text02: "- Veille", 
//     txt23: "- Persona", 
//     txt24: "- UserJournay et Flowchart", 
//     txt25: "- Outils de design thinking tel que 5W1H", 
//     txt26: "- Facilitation", 
//     img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/research/03.png?raw=true",
//     title02: "Prototyping",
//     ENtext03: "- UserJourney", 
//     ENtxt33: "- Level Design", 
//     ENtxt34: "- Low-fidelity prototype", 
//     ENtxt35: "- Testing and iteration", 
//     ENtxt36: "- Presentation", 
//     text03: "- UserJourney", 
//     txt33: "- Level Design", 
//     txt34: "- Prototype low-fidelity", 
//     txt35: "- Test et itération", 
//     txt36: "- Présentation",
//     none: "-   ", 
// };
const these = {
    Where:"Cnam-Enjmin",
    Where2: "Gobelins - École de l'image",
    Title01: "Catégories",
    info01: "Thèse",
    info012: "Accessibilité et technologie XR",
    Title02: "Rôles",
    info02: "UX Research",
    info022: "Presentation et facilitation",
    Title03: "Années",
    info03: "2022 - Aujourd'hui",
    Title04: "Outils",
    info04: "Unity, Blender, Notion, Indesign ...",
    ResumeTitle: "Résumé",
    ResumeTxt: "L’accessibilité et les technologies XR sont des sujets que j’ai à plusieurs reprises rencontrés et sur lequel je travaille encore actuellement. À la base, cette étude a commencé avec ma thèse de fin d’étude, thèse de mastère spécialisé réalisé en 6 mois pendant notre alternance. Lorsqu'on parle de personne en situation de handicap, le mot situation est important, une personne est en situation de handicap lorsque son environnement n'est pas en adéquation avec ses besoins, résultant ainsi d'une barrière. Or, à ce jour, 1 personne sur 6 (d'après un rapport de l'INSEE de 2018) est en situation de handicap en France. Face a ce constat et au retour de collègue et de proche, j'ai commencé mes recherches sur l'accessibilité à travers des technologies immersives. Car si je ne peux pas toujours transformer le réel pour le rendre accessible, est-ce que le virtuel pourrait aider à le rendre accessible ?",
    GoalsTitle: "Objectif",
    GoalsTxt:"L'objectif de cette étude était de définir si les technologies XR peuvent être une source d'aide pour les personnes en situation de handicap, mais également quel élément doivent être pris en compte lors du développement de l'expérience. ",
    GoalsTxt2: "Personnellement, mon objectif était également de pouvoir travailler au plus proche des utilisateurs finals et également de sensibiliser sur le sujet. Dans mes recherches, une partie importante fut de réaliser des documents pour partager ce que je trouvais. Les éléments de langage et les points mis en avant évoluant en fonction des interlocuteurs. J'ai ainsi travaillé sur la facilitation du message, et essayer de développer de l'empathie lors de la création de mon discours. Pour certain l'humain était au centre de mon discours, pour d'autres l'idée de performance ou encore l'idée de généralisation (rendre accessible pour une personne facilite l'expérience pour plusieurs).",
    DeroulementTxt: "Au commencement de mes recherches, j'ai dû réaliser des choix sur les thèmes abordés. Dans un premier temps j'ai fait le choix de réaliser mes recherches autour de ce handicap cognitif et dans le cadre du travail. L'idée étant d'évoluer par étapes, avec des itérations. Après une première phase de recherche pour mieux comprendre les enjeux, une étape d'entretiens qualitatifs a été effectuée pour mieux comprendre les problématiques rencontrées dans le cadre du travail, sur l'image qu'ils perçoivent de leur handicap, des démarches qu'ils ont ou non effectuées pour être reconnus par la médecine du travail et des aides qu'ils reçoivent ou non. Cela m'a permis d'identifier plusieurs problématiques récurrentes et également un moment spécifique sur lequel se focaliser dans un premier temps, la réunion. La réunion est ainsi devenue le moment à faire évoluer, ainsi en croisant les différents entretiens j'ai pu décrire le prototype à effectuer et les points cruciaux à mettre en place, notamment la possibilité de choisir, de modifier et régler en fonction de ses besoins.",
    DeroulementTxt2: "À ce jour, la phase de prototypage est en pause et a été analysé à partir de traiter scientifique, faute de moyens humains et techniques. Toutefois, le projet n'a pas été abandonné, il évolue encore à travers un travail de sensibilisation, de facilitation. De mon côté, je cherche toujours à prendre en compte l'accessibilité lors de la production d'expérience, lors de la réalisation de modèle 3D, de leur intégration par rapport à l'utilisateur, le déroulement, et comment prendre contact avec les utilisateurs.",
    Img1: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/01.png?raw=true",
    Img2: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/02.png?raw=true",
    Img3: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/03.png?raw=true",
    Img4: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/04.png?raw=true",
    Img5: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/05.png?raw=true",
    
    nextLink:"/portfolio/VirtualReality",
    backLink:"/portfolio/Workshop",

    
    // title: "Resume",
    // resume: "L’accessibilité et les technologies XR sont des sujets que j’ai à plusieurs reprise rencontrées et sur lequel je travaille encore actuellement. A la base, cette étude a commencé avec ma thèse de fin d’étude, thèse de mastère spécialisé réalisé en 6 mois pendant notre alternance.",
    // resumeEN: "The accessibility in XR technologies is a subject that I have encountered several times and on which I am still working. Basically, this study started with my end-of-study thesis, a specialised master's thesis carried out in 6 months during our apprenticeship.",

    // titleObj: "Goals",
    // objectif: "L'objectif de cette étude était de définir si les technologies XR peuvent être une source d'aide pour les personnes en situation de handicap, mais également de voir quels points doivent être pris en compte pour rendre le contenu accessible.",
    // objectifEN: "The aim of this study was to define whether XR technologies can be a source of help for people with disabilities, but also to see what points need to be taken into account to make content accessible.",
    // img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/01.png?raw=true",   
    // img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/02-ux.png?raw=true",
    // title03: "UX-UI design",
    // ENtext02: "- Qualitative interviews", 
    // ENtxt23: "- QA testing", 
    // ENtxt24: "- Mockup and Wireframe", 
    // ENtxt25: "- UserJourney", 
    // ENtxt26: "- Facilitation", 
    // text02: "- Entretiens qualitatifs", 
    // txt23: "- QA testing", 
    // txt24: "- Mockup et Wireframe", 
    // txt25: "- UserJourney", 
    // txt26: "- Facilitation", 
    // img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/these/03.png?raw=true",
    // title02: "Research",
    // ENtext03: "- Technology watch", 
    // ENtxt33: "- Prototyping", 
    // ENtxt34: "- Reading scientific reports", 
    // ENtxt35: "- Facilitation", 
    // ENtxt36: "- Presentation", 
    // text03: "- Veille technologique", 
    // txt33: "- Prototypage", 
    // txt34: "- Lecture de rapport scientifique", 
    // txt35: "- Facilitation", 
    // txt36: "- Présentation",
    // none: "-   ", 
};
const VR = {
    Title01: "Catégories",
    info01: "Virtual Reality project",
    info012: "Onboarding",
    Title02: "Rôles",
    info02: "UX-UI Design",
    info022: "Level Design",
    info023: "Développement et intégration",
    Title03: "Années",
    info03: "2023",
    Title04: "Outils",
    info04: "Unity, Blender, Figma, FigJam, ...",
    ResumeTitle: "Résumé",
    ResumeTxt: "Lors de mes premiers projet VR réalisé pour mon entreprise, nous nous sommes rendus compte que les utilisateurs cible n'avaient pas ou peu l'habitude d'utiliser les controllers mis à disposition et rendant difficile la prise en main. Un projet annexe, à vu le jour avec pour objectif de proposer une salle d'onboarding, pouvant évoluer en fonction des controllers et permettant aux utilisateurs de prendre en main les controlles en prenant leurs temps.",
    GoalsTitle: "Objectif",
    GoalsTxt:"L'objectif premier de ce projet était de trouver un moyen permettant aux utilisateurs de prendre en main l'outil et de communiquer avec eux tout au long de l'expérience VR. L'idée était de produire des HUD en 3D permettant de partager des informations aux utilisateurs, au final le projet à évoluer et l'idée fut de proposer une salle d'onboarding, sorte de laboratoire ou l'utilisateur pourrait apprendre les intéraction principal avant de rentrer dans la vrai expérience. Il s'agirait d'un avant niveau pour les utilisateurs debutant, permettant de prendre en main des controlles de base tel que la téléportation, la selection ou même la prise en main d'un objet.",
    GoalsTxt2: "",
    DeroulementTxt: "Dans un premier temps un travail sur la priorisation des controlles à été fait, afin de définir lesquels sont les plus important et dans quel ordre faut il les apprendre. Ainsi un travail de Level design en a découler. L'idée étant de définir le format que cela pourrait prendre et comment faire évoluer l'utilisateur sans le perdre. Puis s'en est suivi un travail de modélisation 3D, d'intégration et de développement",
    DeroulementTxt2: "Le niveau ce découpe ainsi en deux partie, une partie d'apprentissage et une partie libre ou l'utilisateur est invité à tester ce qu'il à appris. En parallèle de ce niveau, un UI kit à commencé à être développer afin de faciliter le partage d'information dans l'experience et d'ajouter des rappels, signe et feedback.",
    Img1: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/001.png?raw=true",
    Img2: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/002.png?raw=true",
    Img3: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/003.png?raw=true",
    Img4: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/004.png?raw=true",
    Img5: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/005.png?raw=true",
    
    nextLink:"/portfolio/MixedReality",
    backLink:"/portfolio/These",

    // title: "Resume",
    // resume: "Production de projet en VR, présentation, démonstration et mise en place pour expliquer la prise en main de contrôler.",
    // resumeEN: "Production of VR projects, presentation, demonstration and set-up to explain the handling of the controls.",
    // description: "here",
    // link_game: "https://shynis.itch.io/ice-cubes",
    // titleObj: "Goals",
    // objectif: "Ice Cube est un projet de fin d'étude réalisé en parallèle de notre alternance. Nous étions un groupe de quatre et devions réaliser en moins de 6 mois une première expérience du jeu permettant de comprendre son principe. Nous avons réalisé un onboarding d'un plateformer narratif. Pendant la phase de production, j’ai tenu le rôle de Directrice Artistique, Lead Art et ai également tenu le rôle de Level Designer, UX & Motion Designer.",
    // objectifEN: "Ice Cube is an end-of-study project carried out in parallel with our work-study program. We were a group of four, and in less than 6 months we had to create a first experience of the game, enabling us to understand its principle. We carried out onboarding for a narrative platformer. During the production phase, I took on the role of Art Director, Lead Art and also Level Designer, UX & Motion Designer.",
    // img_link01: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/01.png?raw=true",   
    // img_link02: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/02.png?raw=true",
    // title03: "UX-UI design",
    // text02: "- Facilitation", 
    // txt23: "- Présentation", 
    // txt24: "- Affordance et ergonomie", 
    // txt25: "- Mockup and wireframe", 
    // txt26: "- Étude de l'utilisateur (persona, userjourney ...)", 
    // ENtext02: "- Facilitation", 
    // ENtxt23: "- Presentation", 
    // ENtxt24: "- Affordability and ergonomy", 
    // ENtxt25: "- Mockup et wireframe", 
    // ENtxt26: "- User study (persona, userjourney ...)", 
    // img_link03: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/VirtualReality/03.png?raw=true",
    // title02: "Level Design & Onboarding",
    // ENtext03: "- Level pacing", 
    // ENtxt33: "- Design of the environment and placement of the elements needed for the puzzle", 
    // ENtxt34: "- Prioritization of tasks", 
    // ENtxt35: "- Flow of the levels to guide the players", 
    // ENtxt36: "- Schematization of the placement of set elements", 
    // text03: "- Rythme des niveaux", 
    // txt33: "- Conception de l'environnement et placement des éléments nécessaire pour l'énigme", 
    // txt34: "- Priorisation des tâches", 
    // txt35: "- Cheminement des niveaux pour guider les joueurs", 
    // txt36: "- Schématisation de la mise en place des éléments de décors",
    // none: "-   ", 
};
const workshop = {
    Title01: "Catégories",
    info01: "Workshop",
    info012: "Design Thinking",
    info013: "Facilitation",
    Title02: "Rôles",
    info02: "UX Design",
    Title04: "Outils",
    info04: "Figma, FigJam, PowerPoint, Papier, Post-it...",
    ResumeTitle: "Résumé",
    ResumeTxt: "Séance de workshop réalisé à plusieurs reprises et avec différents publics (professionnel et étudiant). Découpage dès workshop en fonction des objectifs : Discovery workshop, Empathy workshop, Design workshop, Priorization workshop, Critique workshop. ",
    GoalsTitle: "Objectif",
    GoalsTxt:"L'objectif lors de la mise en place d'un workshop est d'identifier quel est l'objectif, pour qui il est destiné, et le temps alloué. Lorsque c'est défini, il faut préparer le workshop, c'est-à-dire son emploi du temps, le matériel nécessaire et si cela se passe en distancier, hybride ou présentiel.",
    GoalsTxt2:"Puis il y a le moment du workshop, l'objectif à ce moment-là est d'accompagner les participants, les aider à chaque étape pour leur permettre d'effectuer les différents ateliers, c'est-à-dire leur expliquer, leur rappeler l'objectif, les encadrer un minimum et les pousser à se surpasser. En effet, lorsque je connais l'équipe avec qui je travaille, j'ai pour habitude de sélectionner un atelier d'ice-breaking permettant des travailleurs points faibles, comme le team building, la créativité… de même l'ice-breaking permet de mettre dans le bain et d'introduire les objectifs de la journée.",
    DeroulementTxt: "Un workshop se déroule en plusieurs étapes, la première est la préparation (comme expliqué précédemment), on retrouve ensuite le workshop où l'on retrouve une présentation des objectifs de la journée, l'ice-breaking, les ateliers, sans oublier les pauses. Il peut arriver par moments qu'un atelier nécessite plus de temps, dans ce cas, il faut réussir à prioriser et faire évoluer la suite des ateliers pour ne pas dépasser l'heure notée. À la fin du workshop, un compte rendu et un Rex est apprécié et nous permet de nous améliorer. Un compte rendu du workshop est souhaité pour permettre aux participants d'avoir une trace de l'événement.",
    DeroulementTxt2: "Ayant eu la possibilité d'effectuer des workshops auprès de différents types de participant, cela m'a permis de m'améliorer et de ne pas hésiter à rester flexible tout au long de la journée. Il ne faut pas falloir également par moments de prendre le temps de bien expliquer un exercice, et s'il se passe bien et apporte beaucoup à notre objectif, permettre de rallonger le temps que l'on y consacre. Bien évidemment, au contraire, il peut arriver qu'un atelier doive être modifié en fonction des aptitudes des participants, par exemple s'ils ont du mal à réaliser un atelier d'idéation par écrit, peut-être sur un atelier de dessin peut être profitable.",
    Img1: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/workshop/001.png?raw=true",
    Img2: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/workshop/002.png?raw=true",
    Img3: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/workshop/003.png?raw=true",
    Img4: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/workshop/004.png?raw=true",
    Img5: "https://github.com/stevensmt/portfolio/blob/master/src/pages/portfolio/workshop/005.png?raw=true",
    
    nextLink:"/portfolio/These",
    backLink:"/portfolio/IceCube",
};



const socialprofils = {
    cv: "https://github.com/stevensmt/portfolio/blob/master/src/pages/home/img/cv.png?raw=true",
    linkedin: "https://www.linkedin.com/in/margot-stevens-162303185/",
    email: "m.stevens@protonmail.com",
};
export {
    meta,
    dataabout,
    dataportfolio,
    worktimeline,
    jobtimeline,
    skills,
    learn,
    services,
    introdata,
    socialprofils,
    logotext,
    icecube,
    MR,
    these,
    VR,
    workshop,
};